### ISSUE TITLE
ListReportsCommand causes NullPointerException

### ISSUE THREAD

**Issue by Acquized** [Acquized/ProjectRetile#7]
_At friday, 28th of October at 3:36 PM the user @Jumpstyle135 submited a 2-star review on SpigotMC.org:_

![Spigot](http://image.prntscr.com/image/d0a324ee5d424c6dae07f9316a4d1145.png)
Addition at the end of the review:

```
10:55:52 [GRAVE] Exception in thread "main" 
10:55:52 [GRAVE] java.io.IOException: Erreur d'entrée/sortie
10:55:52 [GRAVE] at java.io.FileInputStream.read(Native Method)
10:55:52 [GRAVE] at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
10:55:52 [GRAVE] at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137)
10:55:52 [GRAVE] at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246)
```

**This issue requires more information.** It won't be proceeded / closed / re-opened until more information has been provided by the Spigot user.

**Comment by Jumpstyle135** [comment]
Excuse me, I had not noticed that it was necessary to post on github. these errors are displayed in the Proxy logs more since I installed my mysql crashes and said "too many connections" you can help me?

**Comment by Acquized** [comment]
Alright, that is a problem with connection pooling. ProjectRetile uses connection pooling to keep many available connections alive and to pararell execute SQL commands for better performance. A few MySQL servers don't allows as much connections as it should. You can configure how many connections should be kept alive during idling and how many maximal. For this, take a look in the config.yml and change the following variables:
```yaml
Pools:
  # How many connections should be keept alive when idling?
  MinimumPoolIdleSize: 5 # <- Lower this value
  # How many connection should be max. used?
  MaximalPoolSize: 20 # <- Lower this value
  # How long should we try to keep a connection alive until we mark it as timed out?
  # Set higher if your database server is hosted somewhere completly else
  PoolTimeOut: 3000
```
You need to experiment with the values. If no errors occur, keep the setting. For minimal settings, set both values to `1`. This may cause lags when reporting.
